// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17jqnuzbCBON5F8wKEodcK7rq188qsCw',
    appId: '1:912736876685:web:2ce8d514bcf0e85a990ac4',
    messagingSenderId: '912736876685',
    projectId: 'notesflutterproject',
    authDomain: 'notesflutterproject.firebaseapp.com',
    storageBucket: 'notesflutterproject.appspot.com',
    measurementId: 'G-MRF5TEZEMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwqqmnjQq9b3W4j4NWWAMgABPUKO1XV0',
    appId: '1:912736876685:android:31428839a05dc713990ac4',
    messagingSenderId: '912736876685',
    projectId: 'notesflutterproject',
    storageBucket: 'notesflutterproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNQyuDEEq6h0-MTzfYC3R7Ihuy4DXzW0',
    appId: '1:912736876685:ios:b34117a94efbdadf990ac4',
    messagingSenderId: '912736876685',
    projectId: 'notesflutterproject',
    storageBucket: 'notesflutterproject.appspot.com',
    androidClientId: '912736876685-ngkl9g8ptcj883stbimh829a2ktmsps1.apps.googleusercontent.com',
    iosClientId: '912736876685-duoetbas98ke1sncdmf4jatfg5tbevea.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNQyuDEEq6h0-MTzfYC3R7Ihuy4DXzW0',
    appId: '1:912736876685:ios:f1a5854c74fac4d7990ac4',
    messagingSenderId: '912736876685',
    projectId: 'notesflutterproject',
    storageBucket: 'notesflutterproject.appspot.com',
    androidClientId: '912736876685-ngkl9g8ptcj883stbimh829a2ktmsps1.apps.googleusercontent.com',
    iosClientId: '912736876685-qc8aabtmnp8882gc4h7mqcss0qfe29ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesTrivia.RunnerTests',
  );
}
